<#
.SYNOPSIS
    Promote a skill, an agent, or an agent + its supporting skills from a
    source repo (e.g. agent-plugins-personal) into this public agent-skills
    repo as a single plugin entry.

.DESCRIPTION
    Promotion unit = one plugin in plugins.yml. A plugin can bundle:
      - one skill (the common "graduate a skill to public" case)
      - one agent + N supporting skills (the agent-with-multiple-skills case)
      - N skills with no agent
      - one agent with no skills

    What this script does:
      1. Validates the source skill folder(s) and/or agent file(s) exist and
         that the destination paths are not already taken (unless -Force).
        2. Runs scripts/scan-leaks.ps1 against source paths to catch secrets
            and sensitive identifiers before any files are copied (unless
            -SkipScan is set).
        3. Copies each skill folder to src/skills/<name>/ and each agent file
         to src/agents/<name>.agent.md.
        4. Rewrites the source repo name to this repo's name in copied .md
         files (handles `<repo>/src/skills/...` paths, marketplace add
         commands, and `<skill>@<repo>` install commands in one substitution).
        5. Appends (or -Force-replaces) the plugin entry in plugins.yml,
         preserving the existing file's formatting.
        6. Runs scripts/build-plugins.ps1 to materialize plugins/<plugin>/.
        7. Runs scripts/lint.ps1 to validate frontmatter, version coherence,
         and src/->plugins/ drift.

    The script never edits anything under plugins/ directly — that tree is
    regenerated by build-plugins.ps1 from src/ + plugins.yml.

    Use -DryRun to preview the plan without writing anything.

.PARAMETER Name
    Plugin key to use in plugins.yml. By convention, single-skill plugins
    use the skill's folder name; agent-led plugins use the agent's name.

.PARAMETER SkillSource
    One or more full paths to skill folders in the source repo (each folder
    must contain SKILL.md). The folder name becomes the destination skill
    name under src/skills/.

.PARAMETER AgentSource
    One or more full paths to *.agent.md files in the source repo. The
    portion before .agent.md becomes the agent's name under src/agents/.

.PARAMETER Description
    Single-line description used as the `description:` field in the
    plugins.yml entry. If it contains ': ' (colon + space) it will be
    automatically double-quoted to keep YAML parsing happy.

.PARAMETER Version
    Plugin version (e.g. 1.0.0). If omitted and the plugin's `Name` matches
    one of the skills in `SkillSource`, the version is derived from that
    skill's SKILL.md frontmatter `version:`.

.PARAMETER Keywords
    Array of keywords for the plugins.yml entry.

.PARAMETER OldRepoName
    Source repo's bare name (without owner). Default: agent-plugins-personal.
    All occurrences of this string in copied .md files are rewritten to
    -NewRepoName. This catches `<owner>/<OldRepoName>/src/skills/...`,
    `<owner>/<OldRepoName>` (Copilot marketplace add), and
    `<skill>@<OldRepoName>` (Copilot install) in one substitution.

.PARAMETER NewRepoName
    Replacement bare name. Default: agent-skills.

.PARAMETER Force
    Overwrite existing src/skills/<name>/, src/agents/<name>.agent.md, and
    the plugins.yml entry for `Name` if any are already present.

.PARAMETER DryRun
    Print the promotion plan and exit. No files written, no build, no lint.

.PARAMETER SkipBuild
    Skip the final build-plugins.ps1 + lint.ps1 step. Useful if you plan to
    promote multiple skills back-to-back and run the build once at the end.

.PARAMETER SkipScan
    Skip scripts/scan-leaks.ps1. Not recommended for normal promotion flows.

.EXAMPLE
    # Promote a single skill (skill becomes its own plugin)
    pwsh scripts/promote-skill.ps1 `
      -Name my-cool-skill `
      -SkillSource "..\agent-plugins-personal\src\skills\my-cool-skill" `
      -Description "Short single-line description" `
      -Keywords kw1,kw2,kw3

.EXAMPLE
    # Promote an agent that depends on two supporting skills as one plugin
    pwsh scripts/promote-skill.ps1 `
      -Name release-helper `
      -AgentSource "..\agent-plugins-personal\src\agents\release-helper.agent.md" `
      -SkillSource @(
          "..\agent-plugins-personal\src\skills\version-bump",
          "..\agent-plugins-personal\src\skills\changelog-gen"
      ) `
      -Description "Drives a release. Bumps versions, regenerates changelog, opens PR." `
      -Version 1.0.0

.EXAMPLE
    # Preview only
    pwsh scripts/promote-skill.ps1 -Name foo `
      -SkillSource ..\foo -Description "bar" -DryRun
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string]$Name,
    [string[]]$SkillSource = @(),
    [string[]]$AgentSource = @(),
    [Parameter(Mandatory)] [string]$Description,
    [string]$Version,
    [string[]]$Keywords = @(),
    [string]$License = 'MIT',
    [string]$Category = 'development',
    [string]$Homepage,
    [string]$Repository = 'https://github.com/rwilson504/agent-skills',
    [string]$OldRepoName = 'agent-plugins-personal',
    [string]$NewRepoName = 'agent-skills',
    [switch]$Force,
    [switch]$DryRun,
    [switch]$SkipBuild,
    [switch]$SkipScan,
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot/..").Path
)

$ErrorActionPreference = 'Stop'

# ---------- Validate arguments ----------
if ($SkillSource.Count -eq 0 -and $AgentSource.Count -eq 0) {
    throw "Provide at least one of -SkillSource or -AgentSource."
}
if ($Name -notmatch '^[a-z0-9][a-z0-9-]*$') {
    throw "Plugin -Name must match ^[a-z0-9][a-z0-9-]*$ (ClawHub slug rule). Got: '$Name'"
}
if (-not $Homepage) {
    $Homepage = "https://github.com/rwilson504/agent-skills/tree/main/plugins/$Name"
}

# ---------- Resolve and validate sources ----------
$skillSources = @()
foreach ($s in $SkillSource) {
    if (-not (Test-Path $s)) { throw "Skill source not found: $s" }
    $resolved = (Resolve-Path $s).Path
    if (-not (Test-Path -PathType Container $resolved)) {
        throw "Skill source must be a directory: $resolved"
    }
    if (-not (Test-Path (Join-Path $resolved 'SKILL.md'))) {
        throw "Skill source missing SKILL.md: $resolved"
    }
    $skillName = Split-Path $resolved -Leaf
    if ($skillName -notmatch '^[a-z0-9][a-z0-9-]*$') {
        throw "Skill folder name must match ^[a-z0-9][a-z0-9-]*$. Got: '$skillName'"
    }
    $skillSources += [pscustomobject]@{
        SourcePath = $resolved
        Name       = $skillName
    }
}

$agentSources = @()
foreach ($a in $AgentSource) {
    if (-not (Test-Path $a)) { throw "Agent source not found: $a" }
    $resolved = (Resolve-Path $a).Path
    if ($resolved -notmatch '\.agent\.md$') {
        throw "Agent source must end with .agent.md: $resolved"
    }
    $agentName = (Split-Path $resolved -Leaf) -replace '\.agent\.md$', ''
    if ($agentName -notmatch '^[a-z0-9][a-z0-9-]*$') {
        throw "Agent file name must match ^[a-z0-9][a-z0-9-]*\.agent\.md$. Got: '$agentName.agent.md'"
    }
    $agentSources += [pscustomobject]@{
        SourcePath = $resolved
        Name       = $agentName
    }
}

# ---------- Pre-copy leak/sensitivity scan ----------
if (-not $SkipScan) {
    $scanScript = Join-Path $PSScriptRoot 'scan-leaks.ps1'
    if (-not (Test-Path $scanScript)) {
        throw "Required script not found: $scanScript"
    }

    $scanPaths = @()
    if ($skillSources.Count -gt 0) { $scanPaths += @($skillSources | ForEach-Object { $_.SourcePath }) }
    if ($agentSources.Count -gt 0) { $scanPaths += @($agentSources | ForEach-Object { $_.SourcePath }) }

    Write-Host ''
    Write-Host 'Running pre-copy leak/sensitivity scan...' -ForegroundColor Cyan
    & $scanScript -Path $scanPaths -RepoRoot $RepoRoot
    if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) {
        throw "scan-leaks.ps1 reported findings. Sanitize source content or use -SkipScan to override."
    }
}

# ---------- Derive version from primary skill if needed ----------
if (-not $Version) {
    $primary = $skillSources | Where-Object { $_.Name -eq $Name } | Select-Object -First 1
    if ($primary) {
        $skillMd = Join-Path $primary.SourcePath 'SKILL.md'
        $content = Get-Content $skillMd -Raw
        if ($content -match '^---\s*\r?\n([\s\S]*?)\r?\n---') {
            $fm = $Matches[1]
            if ($fm -match '(?m)^version:\s*(.+?)\s*$') {
                $Version = $Matches[1].Trim().Trim('"').Trim("'")
                Write-Host "Derived -Version $Version from $($primary.Name)/SKILL.md frontmatter" -ForegroundColor DarkGray
            }
        }
    }
    if (-not $Version) {
        throw "-Version not specified and could not be derived. Pass -Version explicitly, or include a skill folder named '$Name' in -SkillSource."
    }
}
if ($Version -notmatch '^\d+\.\d+\.\d+(?:[-+].+)?$') {
    throw "-Version must be semver (e.g. 1.0.0). Got: '$Version'"
}

# ---------- Destinations and conflict detection ----------
$destSkillsRoot = Join-Path $RepoRoot 'src/skills'
$destAgentsRoot = Join-Path $RepoRoot 'src/agents'
$pluginsYml     = Join-Path $RepoRoot 'plugins.yml'

if (-not (Test-Path $destSkillsRoot)) { throw "Missing $destSkillsRoot — run from the agent-skills repo root or pass -RepoRoot." }
if (-not (Test-Path $destAgentsRoot)) { throw "Missing $destAgentsRoot — run from the agent-skills repo root or pass -RepoRoot." }
if (-not (Test-Path $pluginsYml))     { throw "Missing $pluginsYml — run from the agent-skills repo root or pass -RepoRoot." }

$conflicts = @()
foreach ($s in $skillSources) {
    $dst = Join-Path $destSkillsRoot $s.Name
    if (Test-Path $dst) { $conflicts += "src/skills/$($s.Name)/ already exists" }
}
foreach ($a in $agentSources) {
    $dst = Join-Path $destAgentsRoot "$($a.Name).agent.md"
    if (Test-Path $dst) { $conflicts += "src/agents/$($a.Name).agent.md already exists" }
}

$ymlText = Get-Content $pluginsYml -Raw
$escName = [regex]::Escape($Name)
$existingEntryPattern = "(?m)^\s{2}${escName}:\s*$"
$pluginEntryExists = ($ymlText -match $existingEntryPattern)
if ($pluginEntryExists) { $conflicts += "plugins.yml already has an entry for '$Name'" }

if ($conflicts.Count -gt 0 -and -not $Force) {
    Write-Host ''
    Write-Host "Conflicts (re-run with -Force to overwrite):" -ForegroundColor Red
    $conflicts | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    throw "Aborting due to conflicts."
}

# ---------- Build plugins.yml entry text ----------
function ConvertTo-YamlScalar {
    param([string]$Value)
    # Auto-quote if the value contains characters that confuse YAML scalars.
    if ($Value -match ': ' -or $Value -match '^[\[\{\!\|\>\&\*\#\?\,\@\`]' -or $Value -match '\s#') {
        return '"' + ($Value -replace '\\', '\\' -replace '"', '\"') + '"'
    }
    return $Value
}

$entryLines = @()
$entryLines += "  ${Name}:"
$entryLines += "    description: $(ConvertTo-YamlScalar $Description)"
$entryLines += "    version: $Version"
$entryLines += "    license: $License"
$entryLines += "    category: $Category"
$entryLines += "    homepage: $Homepage"
$entryLines += "    repository: $Repository"
if ($Keywords.Count -gt 0) {
    $entryLines += "    keywords:"
    foreach ($kw in $Keywords) { $entryLines += "      - $(ConvertTo-YamlScalar $kw)" }
}
if ($agentSources.Count -gt 0) {
    $entryLines += "    agents:"
    foreach ($a in $agentSources) { $entryLines += "      - $($a.Name)" }
}
if ($skillSources.Count -gt 0) {
    $entryLines += "    skills:"
    foreach ($s in $skillSources) { $entryLines += "      - $($s.Name)" }
}
$entryText = ($entryLines -join "`n") + "`n"

# ---------- Plan summary ----------
Write-Host ''
Write-Host "Promotion plan" -ForegroundColor Cyan
Write-Host "  Plugin name : $Name"
Write-Host "  Version     : $Version"
Write-Host "  Description : $Description"
if ($Keywords.Count -gt 0) {
    Write-Host "  Keywords    : $($Keywords -join ', ')"
}
if ($skillSources.Count -gt 0) {
    Write-Host "  Skills:"
    foreach ($s in $skillSources) {
        Write-Host "    $($s.SourcePath)"
        Write-Host "      -> src/skills/$($s.Name)/"
    }
}
if ($agentSources.Count -gt 0) {
    Write-Host "  Agents:"
    foreach ($a in $agentSources) {
        Write-Host "    $($a.SourcePath)"
        Write-Host "      -> src/agents/$($a.Name).agent.md"
    }
}
if ($OldRepoName -ne $NewRepoName) {
    Write-Host "  Path rewrite: '$OldRepoName' -> '$NewRepoName' (in copied .md files)"
}
if ($pluginEntryExists -and $Force) {
    Write-Host "  plugins.yml : REPLACING existing entry (-Force)" -ForegroundColor Yellow
} else {
    Write-Host "  plugins.yml : appending entry"
}

if ($DryRun) {
    Write-Host ''
    Write-Host "[DryRun] No changes written." -ForegroundColor Yellow
    return
}

# ---------- Copy files ----------
Write-Host ''
Write-Host "Copying files..." -ForegroundColor Cyan
foreach ($s in $skillSources) {
    $dst = Join-Path $destSkillsRoot $s.Name
    if (Test-Path $dst) {
        Remove-Item -Recurse -Force $dst
        Write-Host "  ! removed existing src/skills/$($s.Name)/ (-Force)"
    }
    Copy-Item -Recurse -Force $s.SourcePath $dst
    Write-Host "  + src/skills/$($s.Name)/"
}
foreach ($a in $agentSources) {
    $dst = Join-Path $destAgentsRoot "$($a.Name).agent.md"
    if (Test-Path $dst) {
        Remove-Item -Force $dst
        Write-Host "  ! removed existing src/agents/$($a.Name).agent.md (-Force)"
    }
    Copy-Item -Force $a.SourcePath $dst
    Write-Host "  + src/agents/$($a.Name).agent.md"
}

# ---------- Path rewrites in copied .md files ----------
if ($OldRepoName -and $NewRepoName -and ($OldRepoName -ne $NewRepoName)) {
    $touched = 0
    $rewriteFiles = [System.Collections.Generic.List[string]]::new()
    foreach ($s in $skillSources) {
        $root = Join-Path $destSkillsRoot $s.Name
        Get-ChildItem $root -Recurse -File -Include '*.md', '*.markdown' |
            ForEach-Object { $rewriteFiles.Add($_.FullName) | Out-Null }
    }
    foreach ($a in $agentSources) {
        $rewriteFiles.Add((Join-Path $destAgentsRoot "$($a.Name).agent.md")) | Out-Null
    }
    foreach ($file in $rewriteFiles) {
        $body = Get-Content $file -Raw
        if ($body.Contains($OldRepoName)) {
            $newBody = $body.Replace($OldRepoName, $NewRepoName)
            Set-Content -Path $file -Value $newBody -Encoding UTF8 -NoNewline
            $touched++
            $rel = $file.Substring($RepoRoot.Length).TrimStart('\','/').Replace('\','/')
            Write-Host "  ~ $rel (rewrote '$OldRepoName' -> '$NewRepoName')"
        }
    }
    if ($touched -eq 0) {
        Write-Host "  (no .md files contained '$OldRepoName' — no rewrites needed)" -ForegroundColor DarkGray
    }
}

# ---------- Update plugins.yml ----------
$ymlText = Get-Content $pluginsYml -Raw

if ($pluginEntryExists -and $Force) {
    # Strip existing entry block: from "  <Name>:" through to (but not including)
    # the next "  <something>:" entry or end-of-file.
    $blockPattern = "(?ms)(?:^|\r?\n)  ${escName}:\r?\n(?:    .*\r?\n?)*"
    $ymlText = [regex]::Replace($ymlText, $blockPattern, "`n")
    Write-Host "  ~ removed existing plugins.yml entry for '$Name'"
}

# Normalize: strip all trailing whitespace, then add exactly one final newline.
$ymlText = $ymlText.TrimEnd("`r","`n"," ","`t") + "`n"

# Append a blank-line separator + the new entry (which itself ends with \n).
$newYml = $ymlText + "`n" + $entryText
Set-Content -Path $pluginsYml -Value $newYml -Encoding UTF8 -NoNewline
Write-Host "  + plugins.yml entry for '$Name'"

# ---------- Build + Lint ----------
if (-not $SkipBuild) {
    Write-Host ''
    Write-Host "Running build-plugins.ps1..." -ForegroundColor Cyan
    # '&' runs these in-process, which does NOT set $LASTEXITCODE - it keeps the
    # value left by the last external command. Zero it first or the guard reads a
    # stale code and throws on a build that succeeded.
    $global:LASTEXITCODE = 0
    & (Join-Path $PSScriptRoot 'build-plugins.ps1') -RepoRoot $RepoRoot
    if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) {
        throw "build-plugins.ps1 failed (exit $LASTEXITCODE). Fix the issue and re-run scripts/build-plugins.ps1."
    }

    Write-Host ''
    Write-Host "Running lint.ps1..." -ForegroundColor Cyan
    $global:LASTEXITCODE = 0
    & (Join-Path $PSScriptRoot 'lint.ps1') -RepoRoot $RepoRoot
    if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) {
        throw "lint.ps1 reported errors. Fix them before committing."
    }
}

# ---------- Done ----------
Write-Host ''
Write-Host "Promoted '$Name' (v$Version)" -ForegroundColor Green
Write-Host 'Next steps:'
Write-Host '  1. Review the diff:           git status; git diff'
Write-Host '  2. Spot-check the SKILL.md frontmatter (license: MIT-0, metadata.openclaw.homepage URL)'
Write-Host "  3. Optional: add a row to README.md 'Available Skills' table"
Write-Host '  4. Commit and push'
